# Site settings
title: Daily Development Notes
name: KimJunHee # your name
email: wnsgml972@gmail.com # your email address
description: Software Programmer
baseurl: "/wnsgml972.github.io" # the subpath of your site, e.g. /blog
url: "https://wnsgml972.github.io" # the base hostname & protocol for your site
twitter_username: KimJunHee # your Twitter username
github_username: wnsgml972 # your Github username
disqus_username: wnsgml972-1 # your disqus username

google-analytics: UA-113140483-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown

# Amount of post to show on home page
paginate: 6

# Belongs at: /_data/navigation.yml

- title: Home
  url: /

- title: Group of Things
  url: /group/
  sublinks:
    - title: Sub-item 1
      url: /group/si1
    - title: Sub-item 2
      url: /group/si2
    - title: Sub-item 3
      url: /group/si3
